"""add external image url columns

Revision ID: 8d39711f89a4
Revises: f8d832c2bad4
Create Date: 2026-07-11 19:43:09.615751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d39711f89a4'
down_revision: Union[str, Sequence[str], None] = 'f8d832c2bad4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('front_image_url', sa.Text(), nullable=True))
    op.add_column('cards', sa.Column('back_image_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cards', 'back_image_url')
    op.drop_column('cards', 'front_image_url')
    # ### end Alembic commands ###
