"""create sets and cards tables

Revision ID: f8d832c2bad4
Revises: 
Create Date: 2026-07-11 19:29:03.516559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f8d832c2bad4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug', name='uq_sets_slug')
    )
    op.create_index(op.f('ix_sets_slug'), 'sets', ['slug'], unique=False)
    op.create_table('cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('set_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('front', sa.Text(), nullable=False),
    sa.Column('back', sa.Text(), nullable=False),
    sa.Column('symbols', sa.Text(), nullable=True),
    sa.Column('matching', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('front_image_key', sa.Text(), nullable=True),
    sa.Column('back_image_key', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['set_id'], ['sets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cards_set_id'), 'cards', ['set_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cards_set_id'), table_name='cards')
    op.drop_table('cards')
    op.drop_index(op.f('ix_sets_slug'), table_name='sets')
    op.drop_table('sets')
    # ### end Alembic commands ###
